In [1]:
import numpy as np
from numpy.linalg import norm

d1 = np.array([1, 0, 1, 0, 1])
d2 = np.array([1, 1, 0, 0, 1])
d3 = np.array([0, 0, 0, 1, 1])
print(d1)
print(d2)
print(d3)

[1 0 1 0 1]
[1 1 0 0 1]
[0 0 0 1 1]


In [2]:
dist_e = norm(d2-d1)
print("Distancia euclidiana entre d1 y d2: {}".format(dist_e))

Distancia euclidiana entre d1 y d2: 1.4142135623730951


In [3]:
dist_e = norm(d2-d3)
print("Distancia euclidiana entre d1 y d3: {}".format(dist_e))

Distancia euclidiana entre d1 y d3: 1.7320508075688772
